apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "1938627226880853132"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sabithaatla/test2
status: {}
