apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "6246873492203351581"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sabithaatla/test2
status: {}
