apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust883654149426198094
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider2flux+cluster2/context/883654149426198094
  prune: true
  sourceRef:
    kind: GitRepository
    name: "883654149426198094"
  targetNamespace: default
status: {}
