apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust8378151766048802154
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider2flux+cluster2/context/8378151766048802154
  prune: true
  sourceRef:
    kind: GitRepository
    name: "8378151766048802154"
  targetNamespace: default
status: {}
