apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust5938180998322942310
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider2flux+cluster2/context/5938180998322942310
  prune: true
  sourceRef:
    kind: GitRepository
    name: "5938180998322942310"
  targetNamespace: default
status: {}
